In [1]:
import numpy as np

In [6]:
A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])

In [8]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [9]:
cal=A.sum(axis=0)

In [10]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [12]:
percentage=100*A/cal
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

## python numpy vectors

In [14]:
a=np.random.rand(5)
print(a)

[0.29859191 0.24606097 0.3854729  0.15019312 0.34947355]


In [15]:
a.shape

(5,)

In [16]:
print(a.T)

[0.29859191 0.24606097 0.3854729  0.15019312 0.34947355]


In [17]:
print(np.dot(a,a.T))

0.4429822197837365


In [18]:
print(np.random.rand(5,1))
print(a)

[[0.77618303]
 [0.56629904]
 [0.80694133]
 [0.72866913]
 [0.87077305]]
[0.29859191 0.24606097 0.3854729  0.15019312 0.34947355]


In [19]:
a.T

array([0.29859191, 0.24606097, 0.3854729 , 0.15019312, 0.34947355])

In [20]:
print(np.dot(a,a.))

0.4429822197837365


<!-- Logistic Regression with a Neural Network mindset -->
Welcome to your second programming assignment, you wil implemant an algorithm rocognizing oat facos on imagos. You wil have to use what you
implemented in the firsi programming assignment ("Python Basios").

<!-- Rules of this assignment:
 -->
. You are not allowed to use any loop (for/while), unless it is oxpliotly state you can.
. Go through the assignment along with our axplanatory assignment vidoo optionnl].

<!-- You will learn toe -->

. Build the genoral architecture of a leaming algorithm, including:
. Ininlizing parameiers
. Calculating the cost function aind its gradiont
. Bulding an optimization function (stochastio gradiont descent)
. Gather all single unctions in a main model function, in the right order.


1) Packages
Let's first import all the packages that you will neod during this nssignment.

. numpy is the fundamental pockage for scientific compuing with Python.
. h5py is a common paokage to internet wih a datnset that is stored on an H5 file.
. matploilb is a famous library to plot graphs in Python.



In [25]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

%matplotlib inline

### START CODE NEMETOON (= 3 Lines of codr)
print ("Hello World")
# O END CODE HERE

Hello World


2) Overview of the Problem set
Problem Statement: You are given a dataset ("data.h5") containing:

- a training set of m_train images labeled as cat (1) or mon-cat (0)
- a test set of m_test images labeled as cat and non-cat
- each image is of shape (num_px, num_px, 3) where 3 is for the 3 chanmels (RGB).

You will build a simple image-recognition algorithm that can correctly classily pictures as cat or non-cat.

Let's get more familiar with the dataset. Load the data by running the following code.



In [30]:
# Loading the data (cot/non-cat)
train_dataset = h5py.File("datasets/traim_catvnoncat.h5", "r")
train_set_x = np.array(traim_dataset["erain_set_x"][:]) # your troin set features
train_set_y = np.array(train_dataset["train_set_y"][:]) #your troin set Lobels

test_dataset = hSpy.File("datasets/test_catvnoncat.h5", "r")
test_set_x = np.array(test_dataset["test.set_x"][:]) # your test set features
test_set_y = p.array(test_dataset["test_set_y"][:]) # your test set Lobels

classes = np.array(test_dataset["list_classes"][:]) # the List of closses

SyntaxError: invalid syntax (1761186405.py, line 4)