In [1]:
import emoji
print(emoji.emojize(':thumbs_up:'))

👍


In [2]:
print(emoji.demojize("👍"))

:thumbs_up:


In [3]:
import  pandas as pd

In [4]:
df=pd.read_csv("emoji_data.csv",header=None)

In [5]:
df.head()

0   1
0  French macaroon is so tasty   4
1             work is horrible   3
2                   I am upset  3 
3               throw the ball  1 
4                    Good joke   2

In [6]:
emoj = {
    0: ":red_heart:",
    1: ":cricket_game:",
    2: ":beaming_face_with_smiling_eyes:",
    3: ":pensive_face:",
    4: ":face_savoring_food:"
}

# Function to convert label to emoji
def to_emoji(label):
    return emoji.emojize(emoj[label])

In [7]:
to_emoji(0)

'❤️'

In [8]:
x=df[0].values

In [9]:
x

array(['French macaroon is so tasty', 'work is horrible', 'I am upset',
       'throw the ball', 'Good joke',
       'what is your favorite baseball game', 'I cooked meat',
       'stop messing around', 'I want chinese food',
       'Let us go play baseball', 'you are failing this exercise',
       'yesterday we lost again', 'Good job', 'ha ha ha it was so funny',
       'I will have a cheese cake', 'Why are you feeling bad',
       'I want to joke', 'I never said yes for this',
       'the party is cancelled', 'where is the ball', 'I am frustrated',
       'ha ha ha lol', 'she said yes', 'he got a raise',
       'family is all I have', 'he can pitch really well',
       'I love to the stars and back', 'do you like pizza ',
       'You totally deserve this prize', 'I miss you so much',
       'I like your jacket ', 'she got me a present',
       'will you be my valentine', 'you failed the midterm',
       'Who is down for a restaurant', 'valentine day is near',
       'Great so awesome

In [10]:
y=['4', '3', '3 ', '1 ', '2', '1', '4', '3', '4', '1', '3', '3 ', '2',
       '2', '4', '3', '2', '3 ', '3 ', '1', '3 ', '2', '2', '2', '0', '1',
       '0', '4 ', '2', '0', '2', '0', '0', '3 ', '4', '0', '2', '1',
       '3', '1', '0', '4', '0 ', '3', '0 ', '4', '2', '3 ', '4', '2 ',
       '2', '3', '0', '2', '2', '3 ', '2', '3', '2', '2', '3 ', '3', '0 ',
       '2', '3', '0', '2', '0', '0 ', '2', '3', '2', '4', '1', '3', '3',
       '0', '0', '3', '2', '0', '3', '0', '2', '2', '4', '2', '2', '0',
       '0', '2', '3', '0', '4', '2', '1', '2', '3', '3', '2', '3', '0',
       '3', '0', '2', '0', '2', '3', '4', '3', '1', '3', '4', '3', '2',
       '3', '3', '3', '1', '4', '4', '2', '2', '1', '1', '2', '3', '2',
       '3', '4', '2', '3', '0', '2', '0', '0', '4', '3', '4', '2', '3',
       '2', '3', '4', '2', '1', '2', '4', '3', '1', '3', '2', '3', '2',
       '2', '3', '3', '2', '4', '0', '0', '0', '3', '0', '0', '1', '1',
       '2', '2', '2', '0', '3', '2', '3', '3', '1', '2', '2', '4', '2',
       '3', '1', '2']

In [11]:
f=open('glove.6B.100d.txt','r',encoding='utf8')
c=f.readlines()

# f.close()

In [12]:
embedding={}

In [13]:
import numpy as np
for line in c:
    line=line.split()
    embedding[line[0]]=np.array(line[1:],dtype=float)

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [15]:
tokenizer=Tokenizer()

In [16]:
tokenizer.fit_on_texts(x)
w2i=tokenizer.word_index
xtokens=tokenizer.texts_to_sequences

In [17]:
xtokens=tokenizer.texts_to_sequences(x)
xtokens

[[103, 104, 3, 6, 105],
 [106, 3, 107],
 [1, 7, 108],
 [109, 4, 35],
 [36, 30],
 [37, 3, 19, 110, 26, 49],
 [1, 111, 112],
 [31, 67, 113],
 [1, 20, 114, 27],
 [115, 68, 38, 69, 26],
 [2, 11, 116, 10, 70],
 [117, 50, 71, 51],
 [36, 39],
 [12, 12, 12, 22, 28, 6, 40],
 [1, 32, 21, 5, 118, 119],
 [120, 11, 2, 121, 41],
 [1, 20, 9, 30],
 [1, 72, 52, 53, 13, 10],
 [4, 122, 3, 123],
 [73, 3, 4, 35],
 [1, 7, 124],
 [12, 12, 12, 54],
 [14, 52, 53],
 [15, 23, 5, 125],
 [126, 3, 127, 1, 21],
 [15, 74, 128, 129, 75],
 [1, 18, 9, 4, 130, 55, 131],
 [29, 2, 24, 132],
 [2, 133, 134, 10, 135],
 [1, 33, 2, 6, 76],
 [1, 24, 19, 136],
 [14, 23, 16, 5, 137],
 [32, 2, 138, 8, 77],
 [2, 139, 4, 140],
 [141, 3, 56, 13, 5, 78],
 [77, 42, 3, 142],
 [43, 6, 79],
 [29, 2, 21, 5, 35],
 [15, 74, 17, 29, 143],
 [15, 80, 26],
 [50, 57, 81, 5, 144, 44, 145],
 [146, 11, 147],
 [15, 3, 5, 36, 148],
 [72, 149, 9, 16, 51],
 [1, 33, 58],
 [27, 3, 34],
 [1, 7, 150, 59],
 [6, 41, 45, 2, 151, 152, 46, 68],
 [29, 2, 20, 9, 15

In [18]:
w2i

{'i': 1,
 'you': 2,
 'is': 3,
 'the': 4,
 'a': 5,
 'so': 6,
 'am': 7,
 'my': 8,
 'to': 9,
 'this': 10,
 'are': 11,
 'ha': 12,
 'for': 13,
 'she': 14,
 'he': 15,
 'me': 16,
 'not': 17,
 'love': 18,
 'your': 19,
 'want': 20,
 'have': 21,
 'it': 22,
 'got': 23,
 'like': 24,
 'did': 25,
 'baseball': 26,
 'food': 27,
 'was': 28,
 'do': 29,
 'joke': 30,
 'stop': 31,
 'will': 32,
 'miss': 33,
 'life': 34,
 'ball': 35,
 'good': 36,
 'what': 37,
 'go': 38,
 'job': 39,
 'funny': 40,
 'bad': 41,
 'day': 42,
 'great': 43,
 'dinner': 44,
 'that': 45,
 'with': 46,
 'at': 47,
 'of': 48,
 'game': 49,
 'we': 50,
 'again': 51,
 'said': 52,
 'yes': 53,
 'lol': 54,
 'and': 55,
 'down': 56,
 'had': 57,
 'her': 58,
 'fun': 59,
 'smile': 60,
 'lot': 61,
 'working': 62,
 'him': 63,
 'cute': 64,
 'on': 65,
 'lets': 66,
 'messing': 67,
 'us': 68,
 'play': 69,
 'exercise': 70,
 'lost': 71,
 'never': 72,
 'where': 73,
 'can': 74,
 'well': 75,
 'much': 76,
 'valentine': 77,
 'restaurant': 78,
 'awesome': 79,
 'lik

In [19]:
def get_max(df):
    max_len=0
    for sent in df:
        max_len=max(max_len,len(sent))
    return max_len

In [20]:
max_len=get_max(xtokens)
max_len

10

In [21]:
xtrain=pad_sequences(xtokens,maxlen=max_len,padding='post')
xtokens[:3]

[[103, 104, 3, 6, 105], [106, 3, 107], [1, 7, 108]]

In [22]:
xtrain[:3]

array([[103, 104,   3,   6, 105,   0,   0,   0,   0,   0],
       [106,   3, 107,   0,   0,   0,   0,   0,   0,   0],
       [  1,   7, 108,   0,   0,   0,   0,   0,   0,   0]])

In [23]:
embed_s=100
e_matrix=np.zeros((len(w2i)+1,embed_s))

In [24]:
e_matrix[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
for word,a in w2i.items():
    e_vector=embedding[word]
    e_matrix[a]=e_vector

In [26]:
e_matrix[1]

array([-0.046539 ,  0.61966  ,  0.56647  , -0.46584  , -1.189    ,
        0.44599  ,  0.066035 ,  0.3191   ,  0.14679  , -0.22119  ,
        0.79239  ,  0.29905  ,  0.16073  ,  0.025324 ,  0.18678  ,
       -0.31001  , -0.28108  ,  0.60515  , -1.0654   ,  0.52476  ,
        0.064152 ,  1.0358   , -0.40779  , -0.38011  ,  0.30801  ,
        0.59964  , -0.26991  , -0.76035  ,  0.94222  , -0.46919  ,
       -0.18278  ,  0.90652  ,  0.79671  ,  0.24825  ,  0.25713  ,
        0.6232   , -0.44768  ,  0.65357  ,  0.76902  , -0.51229  ,
       -0.44333  , -0.21867  ,  0.3837   , -1.1483   , -0.94398  ,
       -0.15062  ,  0.30012  , -0.57806  ,  0.20175  , -1.6591   ,
       -0.079195 ,  0.026423 ,  0.22051  ,  0.99714  , -0.57539  ,
       -2.7266   ,  0.31448  ,  0.70522  ,  1.4381   ,  0.99126  ,
        0.13976  ,  1.3474   , -1.1753   ,  0.0039503,  1.0298   ,
        0.064637 ,  0.90887  ,  0.82872  , -0.47003  , -0.10575  ,
        0.5916   , -0.4221   ,  0.57331  , -0.54114  ,  0.1076

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding, SimpleRNN
model=Sequential([Embedding(input_dim=len(w2i)+1,
                           output_dim=embed_s,
                           input_length=max_len,
                           weights=[e_matrix]),
                 LSTM(units=16,return_sequences=True),
                 LSTM(units=4),
                 Dense(5,activation='sigmoid')])

In [28]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
y

['4',
 '3',
 '3 ',
 '1 ',
 '2',
 '1',
 '4',
 '3',
 '4',
 '1',
 '3',
 '3 ',
 '2',
 '2',
 '4',
 '3',
 '2',
 '3 ',
 '3 ',
 '1',
 '3 ',
 '2',
 '2',
 '2',
 '0',
 '1',
 '0',
 '4 ',
 '2',
 '0',
 '2',
 '0',
 '0',
 '3 ',
 '4',
 '0',
 '2',
 '1',
 '3',
 '1',
 '0',
 '4',
 '0 ',
 '3',
 '0 ',
 '4',
 '2',
 '3 ',
 '4',
 '2 ',
 '2',
 '3',
 '0',
 '2',
 '2',
 '3 ',
 '2',
 '3',
 '2',
 '2',
 '3 ',
 '3',
 '0 ',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0 ',
 '2',
 '3',
 '2',
 '4',
 '1',
 '3',
 '3',
 '0',
 '0',
 '3',
 '2',
 '0',
 '3',
 '0',
 '2',
 '2',
 '4',
 '2',
 '2',
 '0',
 '0',
 '2',
 '3',
 '0',
 '4',
 '2',
 '1',
 '2',
 '3',
 '3',
 '2',
 '3',
 '0',
 '3',
 '0',
 '2',
 '0',
 '2',
 '3',
 '4',
 '3',
 '1',
 '3',
 '4',
 '3',
 '2',
 '3',
 '3',
 '3',
 '1',
 '4',
 '4',
 '2',
 '2',
 '1',
 '1',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0',
 '4',
 '3',
 '4',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '1',
 '2',
 '4',
 '3',
 '1',
 '3',
 '2',
 '3',
 '2',
 '2',
 '3',
 '3',
 '2',
 '4',
 '0',
 '0',
 '0',
 '3',
 '0',


In [41]:

ytrain = to_categorical(y)
ytrain
# print(ytrain.shape,xtrain.shape)



array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0.

In [42]:
model.fit(xtrain, ytrain, epochs=10)


Epoch 1/10
6/6 [==============================] - 0s 6ms/step - loss: 1.2939 - accuracy: 0.5246
Epoch 2/10
6/6 [==============================] - 0s 7ms/step - loss: 1.2496 - accuracy: 0.5246
Epoch 3/10
6/6 [==============================] - 0s 7ms/step - loss: 1.2025 - accuracy: 0.5574
Epoch 4/10
6/6 [==============================] - 0s 7ms/step - loss: 1.1514 - accuracy: 0.6011
Epoch 5/10
6/6 [==============================] - 0s 7ms/step - loss: 1.0995 - accuracy: 0.6393
Epoch 6/10
6/6 [==============================] - 0s 7ms/step - loss: 1.0488 - accuracy: 0.7104
Epoch 7/10
6/6 [==============================] - 0s 7ms/step - loss: 0.9926 - accuracy: 0.7596
Epoch 8/10
6/6 [==============================] - 0s 6ms/step - loss: 0.9370 - accuracy: 0.8415
Epoch 9/10
6/6 [==============================] - 0s 7ms/step - loss: 0.8836 - accuracy: 0.8852
Epoch 10/10
6/6 [==============================] - 0s 7ms/step - loss: 0.8430 - accuracy: 0.9016


In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 100)           31300     
                                                                 
 lstm (LSTM)                 (None, 10, 16)            7488      
                                                                 
 lstm_1 (LSTM)               (None, 4)                 336       
                                                                 
 dense (Dense)               (None, 5)                 25        
                                                                 
Total params: 39149 (152.93 KB)
Trainable params: 39149 (152.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:

test = ['i am hungry', 'playing', 'in love', 'valentine week']
test_s = tokenizer.texts_to_sequences(test)
xtest = pad_sequences(test_s, maxlen=max_len, padding = 'post')

y_pred = model.predict(xtest)

1/1 [==============================] - 0s 17ms/step


In [45]:
y_pred


array([[0.75366694, 0.1468875 , 0.5838422 , 0.53746367, 0.78295493],
       [0.49995175, 0.47149983, 0.77437997, 0.7585478 , 0.52491   ],
       [0.60281116, 0.30489668, 0.819627  , 0.68631506, 0.5015911 ],
       [0.705435  , 0.1937385 , 0.7097637 , 0.5901254 , 0.6260328 ]],
      dtype=float32)

In [46]:
y_pred = np.argmax(y_pred, axis=1)

y_pred

array([4, 2, 2, 2], dtype=int64)

In [47]:
to_emoji(y_pred[1])

'😁'

In [68]:
test=["i am good","i am bad","eat lunch","baseball afternoon"]
test_s=tokenizer.texts_to_sequences(test)
xtest=pad_sequences(test_s,maxlen=max_len,padding='post')
y_pred1=model.predict(xtest)

1/1 [==============================] - 0s 19ms/step


In [69]:
y_pred1=np.argmax(y_pred )

y_pred1
to_emoji(y_pred[0])

TypeError: unhashable type: 'numpy.ndarray'

In [70]:
for z in range(len(test)):
    print(test[z],to_emoji(y_pred[0]))

TypeError: unhashable type: 'numpy.ndarray'

In [63]:
to_emoji(y_pred[1])


TypeError: unhashable type: 'numpy.ndarray'